const express = require("express");
const { escape } = require("querystring");

const router = express.Router();
const elements = [
   { id: 1, symbol: "H", name: "Hidrógeno", type: "No metal" },
   { id: 2, symbol: "He", name: "Helio", type: "Gas noble" },
   { id: 3, symbol: "Li", name: "Litio", type: "Alcalino" },
   { id: 4, symbol: "Be", name: "Berilio", type: "Alcalinotérreo" },
   { id: 5, symbol: "B", name: "Boro", type: "Metaloide" },
   { id: 6, symbol: "C", name: "Carbono", type: "No metal" },
   { id: 7, symbol: "N", name: "Nitrógeno", type: "No metal" },
   { id: 8, symbol: "O", name: "Oxígeno", type: "No metal" },
   { id: 9, symbol: "F", name: "Flúor", type: "Halógeno" },
   { id: 10, symbol: "Ne", name: "Neón", type: "Gas noble" },
   { id: 11, symbol: "Na", name: "Sodio", type: "Alcalino" },
   { id: 12, symbol: "Mg", name: "Magnesio", type: "Alcalinotérreo" },
   { id: 13, symbol: "Al", name: "Aluminio", type: "Metal" },
   { id: 14, symbol: "Si", name: "Silicio", type: "Metaloide" },
   { id: 15, symbol: "P", name: "Fósforo", type: "No metal" },
   { id: 16, symbol: "S", name: "Azufre", type: "No metal" },
   { id: 17, symbol: "Cl", name: "Cloro", type: "Halógeno" },
   { id: 18, symbol: "Ar", name: "Argón", type: "Gas noble" },
   { id: 19, symbol: "K", name: "Potasio", type: "Alcalino" },
   { id: 20, symbol: "Ca", name: "Calcio", type: "Alcalinotérreo" },
   { id: 21, symbol: "Sc", name: "Escandio", type: "Metal de transición" },
   { id: 22, symbol: "Ti", name: "Titanio", type: "Metal de transición" },
   { id: 23, symbol: "V", name: "Vanadio", type: "Metal de transición" },
   { id: 24, symbol: "Cr", name: "Cromo", type: "Metal de transición" },
   { id: 25, symbol: "Mn", name: "Manganeso", type: "Metal de transición" },
   { id: 26, symbol: "Fe", name: "Hierro", type: "Metal de transición" },
   { id: 27, symbol: "Co", name: "Cobalto", type: "Metal de transición" },
   { id: 28, symbol: "Ni", name: "Níquel", type: "Metal de transición" },
   { id: 29, symbol: "Cu", name: "Cobre", type: "Metal de transición" },
   { id: 30, symbol: "Zn", name: "Zinc", type: "Metal de transición" },
   { id: 31, symbol: "Ga", name: "Galio", type: "Metal" },
   { id: 32, symbol: "Ge", name: "Germanio", type: "Metaloide" },
   { id: 33, symbol: "As", name: "Arsénico", type: "Metaloide" },
   { id: 34, symbol: "Se", name: "Selenio", type: "No metal" },
   { id: 35, symbol: "Br", name: "Bromo", type: "Halógeno" },
   { id: 36, symbol: "Kr", name: "Kriptón", type: "Gas noble" },
   { id: 37, symbol: "Rb", name: "Rubidio", type: "Alcalino" },
   { id: 38, symbol: "Sr", name: "Estroncio", type: "Alcalinotérreo" },
   { id: 39, symbol: "Y", name: "Itrio", type: "Metal de transición" },
   { id: 40, symbol: "Zr", name: "Circonio", type: "Metal de transición" },
   { id: 41, symbol: "Nb", name: "Niobio", type: "Metal de transición" },
   { id: 42, symbol: "Mo", name: "Molibdeno", type: "Metal de transición" },
   { id: 43, symbol: "Tc", name: "Tecnecio", type: "Metal de transición" },
   { id: 44, symbol: "Ru", name: "Rutenio", type: "Metal de transición" },
   { id: 45, symbol: "Rh", name: "Rodio", type: "Metal de transición" },
   { id: 46, symbol: "Pd", name: "Paladio", type: "Metal de transición" },
   { id: 47, symbol: "Ag", name: "Plata", type: "Metal de transición" },
   { id: 48, symbol: "Cd", name: "Cadmio", type: "Metal de transición" },
   { id: 49, symbol: "In", name: "Indio", type: "Metal" },
   { id: 50, symbol: "Sn", name: "Estaño", type: "Metal" },
   { id: 51, symbol: "Sb", name: "Antimonio", type: "Metaloide" },
   { id: 52, symbol: "Te", name: "Telurio", type: "Metaloide" },
   { id: 53, symbol: "I", name: "Yodo", type: "Halógeno" },
   { id: 54, symbol: "Xe", name: "Xenón", type: "Gas noble" },
   { id: 55, symbol: "Cs", name: "Cesio", type: "Alcalino" },
   { id: 56, symbol: "Ba", name: "Bario", type: "Alcalinotérreo" },
   { id: 57, symbol: "La", name: "Lantano", type: "Lantánido" },
   { id: 58, symbol: "Ce", name: "Cerio", type: "Lantánido" },
   { id: 59, symbol: "Pr", name: "Praseodimio", type: "Lantánido" },
   { id: 60, symbol: "Nd", name: "Neodimio", type: "Lantánido" },
   { id: 61, symbol: "Pm", name: "Prometio", type: "Lantánido" },
   { id: 62, symbol: "Sm", name: "Samario", type: "Lantánido" },
   { id: 63, symbol: "Eu", name: "Europio", type: "Lantánido" },
   { id: 64, symbol: "Gd", name: "Gadolinio", type: "Lantánido" },
   { id: 65, symbol: "Tb", name: "Terbio", type: "Lantánido" },
   { id: 66, symbol: "Dy", name: "Disprosio", type: "Lantánido" },
   { id: 67, symbol: "Ho", name: "Holmio", type: "Lantánido" },
   { id: 68, symbol: "Er", name: "Erbio", type: "Lantánido" },
   { id: 69, symbol: "Tm", name: "Tulio", type: "Lantánido" },
   { id: 70, symbol: "Yb", name: "Iterbio", type: "Lantánido" },
   { id: 71, symbol: "Lu", name: "Lutecio", type: "Lantánido" },
   { id: 72, symbol: "Hf", name: "Hafnio", type: "Metal de transición" },
   { id: 73, symbol: "Ta", name: "Tántalo", type: "Metal de transición" },
   { id: 74, symbol: "W", name: "Wolframio", type: "Metal de transición" },
   { id: 75, symbol: "Re", name: "Renio", type: "Metal de transición" },
   { id: 76, symbol: "Os", name: "Osmio", type: "Metal de transición" },
   { id: 77, symbol: "Ir", name: "Iridio", type: "Metal de transición" },
   { id: 78, symbol: "Pt", name: "Platino", type: "Metal de transición" },
   { id: 79, symbol: "Au", name: "Oro", type: "Metal de transición" },
   { id: 80, symbol: "Hg", name: "Mercurio", type: "Metal de transición" },
   { id: 81, symbol: "Tl", name: "Talio", type: "Metal" },
   { id: 82, symbol: "Pb", name: "Plomo", type: "Metal" },
   { id: 83, symbol: "Bi", name: "Bismuto", type: "Metal" },
   { id: 84, symbol: "Po", name: "Polonio", type: "Metaloide" },
   { id: 85, symbol: "At", name: "Astato", type: "Halógeno" },
   { id: 86, symbol: "Rn", name: "Radón", type: "Gas noble" },
   { id: 87, symbol: "Fr", name: "Francio", type: "Alcalino" },
   { id: 88, symbol: "Ra", name: "Radio", type: "Alcalinotérreo" },
   { id: 89, symbol: "Ac", name: "Actinio", type: "Actínido" },
   { id: 90, symbol: "Th", name: "Torio", type: "Actínido" },
   { id: 91, symbol: "Pa", name: "Protactinio", type: "Actínido" },
   { id: 92, symbol: "U", name: "Uranio", type: "Actínido" },
   { id: 93, symbol: "Np", name: "Neptunio", type: "Actínido" },
   { id: 94, symbol: "Pu", name: "Plutonio", type: "Actínido" },
   { id: 95, symbol: "Am", name: "Americio", type: "Actínido" },
   { id: 96, symbol: "Cm", name: "Curio", type: "Actínido" },
   { id: 97, symbol: "Bk", name: "Berkelio", type: "Actínido" },
   { id: 98, symbol: "Cf", name: "Californio", type: "Actínido" },
   { id: 99, symbol: "Es", name: "Einstenio", type: "Actínido" },
   { id: 100, symbol: "Fm", name: "Fermio", type: "Actínido" },
   { id: 101, symbol: "Md", name: "Mendelevio", type: "Actínido" },
   { id: 102, symbol: "No", name: "Nobelio", type: "Actínido" },
   { id: 103, symbol: "Lr", name: "Lawrencio", type: "Actínido" }
];

let count = 0;


router.get("/", (req, res,next) =>{
   res.render( "index", {layout: false, 
      elements: elements,
      count: count
   })}
);

module.exports = router